social_id: 
  default: ""
  description: 
    en: This is ID
  
social_icon: 
  default: "vk"
  description: 
    en: This is the icon 
    
social_title: 
  default: ""
  description: 
    en: This is the icon    
  
social_link: 
  type: list
  default: "http://vk.com/share.php?url="
  description: 
    en: This is your social link  
