social_id: 
  default: ""
  description: 'This is ID'
  
social_icon: 
  default: ""
  description: 'This is the icon'  
  
social_link: 
  type: list
  default: "http://vk.com/share.php?url="
  description: 'This is your social link'  
